name: Build Solutions

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build-timeserved:
    name: Build TimeServed (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore TimeServed.linux.slnf

      - name: Build
        run: |
          dotnet build TimeServed.linux.slnf \
            --configuration Release \
            --no-restore \
            --output build-output/TimeServed


  build-level-editor:
    name: Build LevelEditor (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore LevelEditor/LevelEditor.sln

      - name: Build
        run: |
          dotnet build LevelEditor/LevelEditor.sln `
            --configuration Release `
            --no-restore `
            --output build-output/LevelEditor
